a = {"data": {"scheduleId": "scd:hirepro-consultancy-pvt-ltd:9143f202-2e15-480a-871b-71ee76609c41", "candidates": [
    {"candidateId": "001590001469588", "products": [{"productId": "prd:pfpi:a98de195-aaee-4e7d-86b7-af847cc09a82",
                                                     "results": {"normId": "global", "scores": {"items": [
                                                         {"name": "Tension-Inquiétude", "value": "26",
                                                          "type": "number"},
                                                         {"name": "Tension-Inquiétude", "value": "5", "type": "number"},
                                                         {"name": "Tension-Inquiétude", "value": "18",
                                                          "type": "number"},
                                                         {"name": "Tension-Inquiétude", "value": "1", "type": "number"},
                                                         {"name": "Confiance en soi", "value": "22", "type": "number"},
                                                         {"name": "Confiance en soi", "value": "1", "type": "number"},
                                                         {"name": "Confiance en soi", "value": "16", "type": "number"},
                                                         {"name": "Confiance en soi", "value": "0", "type": "number"},
                                                         {"name": "Vulnérabilité au stress", "value": "34",
                                                          "type": "number"},
                                                         {"name": "Vulnérabilité au stress", "value": "9",
                                                          "type": "number"},
                                                         {"name": "Vulnérabilité au stress", "value": "26",
                                                          "type": "number"},
                                                         {"name": "Vulnérabilité au stress", "value": "7",
                                                          "type": "number"},
                                                         {"name": "Tolérance à la frustration", "value": "34",
                                                          "type": "number"},
                                                         {"name": "Tolérance à la frustration", "value": "10",
                                                          "type": "number"},
                                                         {"name": "Tolérance à la frustration", "value": "28",
                                                          "type": "number"},
                                                         {"name": "Tolérance à la frustration", "value": "8",
                                                          "type": "number"},
                                                         {"name": "Enthousiasme", "value": "18", "type": "number"},
                                                         {"name": "Enthousiasme", "value": "0", "type": "number"},
                                                         {"name": "Enthousiasme", "value": "12", "type": "number"},
                                                         {"name": "Enthousiasme", "value": "0", "type": "number"},
                                                         {"name": "Sociabilité", "value": "18", "type": "number"},
                                                         {"name": "Sociabilité", "value": "1", "type": "number"},
                                                         {"name": "Sociabilité", "value": "12", "type": "number"},
                                                         {"name": "Sociabilité", "value": "0", "type": "number"},
                                                         {"name": "Energie", "value": "21", "type": "number"},
                                                         {"name": "Energie", "value": "0", "type": "number"},
                                                         {"name": "Energie", "value": "13", "type": "number"},
                                                         {"name": "Energie", "value": "0", "type": "number"},
                                                         {"name": "Assertivité", "value": "19", "type": "number"},
                                                         {"name": "Assertivité", "value": "3", "type": "number"},
                                                         {"name": "Assertivité", "value": "11", "type": "number"},
                                                         {"name": "Assertivité", "value": "0", "type": "number"},
                                                         {"name": "Innovation", "value": "26", "type": "number"},
                                                         {"name": "Innovation", "value": "4", "type": "number"},
                                                         {"name": "Innovation", "value": "20", "type": "number"},
                                                         {"name": "Innovation", "value": "0", "type": "number"},
                                                         {"name": "Gout pour la réflexion", "value": "38",
                                                          "type": "number"},
                                                         {"name": "Gout pour la réflexion", "value": "6",
                                                          "type": "number"},
                                                         {"name": "Gout pour la réflexion", "value": "30",
                                                          "type": "number"},
                                                         {"name": "Gout pour la réflexion", "value": "2",
                                                          "type": "number"},
                                                         {"name": "Analyse de soi", "value": "10", "type": "number"},
                                                         {"name": "Analyse de soi", "value": "0", "type": "number"},
                                                         {"name": "Analyse de soi", "value": "4", "type": "number"},
                                                         {"name": "Analyse de soi", "value": "0", "type": "number"},
                                                         {"name": "Ouverture au changement", "value": "30",
                                                          "type": "number"},
                                                         {"name": "Ouverture au changement", "value": "0",
                                                          "type": "number"},
                                                         {"name": "Ouverture au changement", "value": "22",
                                                          "type": "number"},
                                                         {"name": "Ouverture au changement", "value": "0",
                                                          "type": "number"},
                                                         {"name": "Esprit de compétition", "value": "23",
                                                          "type": "number"},
                                                         {"name": "Esprit de compétition", "value": "3",
                                                          "type": "number"},
                                                         {"name": "Esprit de compétition", "value": "13",
                                                          "type": "number"},
                                                         {"name": "Esprit de compétition", "value": "0",
                                                          "type": "number"},
                                                         {"name": "Attention à autre", "value": "15", "type": "number"},
                                                         {"name": "Attention à autre", "value": "0", "type": "number"},
                                                         {"name": "Attention à autre", "value": "9", "type": "number"},
                                                         {"name": "Attention à autre", "value": "0", "type": "number"},
                                                         {"name": "Confiance en lautre", "value": "38",
                                                          "type": "number"},
                                                         {"name": "Confiance en lautre", "value": "5",
                                                          "type": "number"},
                                                         {"name": "Confiance en lautre", "value": "30",
                                                          "type": "number"},
                                                         {"name": "Confiance en lautre", "value": "1",
                                                          "type": "number"},
                                                         {"name": "Réaction aux conflits", "value": "41",
                                                          "type": "number"},
                                                         {"name": "Réaction aux conflits", "value": "10",
                                                          "type": "number"},
                                                         {"name": "Réaction aux conflits", "value": "33",
                                                          "type": "number"},
                                                         {"name": "Réaction aux conflits", "value": "10",
                                                          "type": "number"},
                                                         {"name": "Plannification organisation", "value": "30",
                                                          "type": "number"},
                                                         {"name": "Plannification organisation", "value": "1",
                                                          "type": "number"},
                                                         {"name": "Plannification organisation", "value": "22",
                                                          "type": "number"},
                                                         {"name": "Plannification organisation", "value": "0",
                                                          "type": "number"},
                                                         {"name": "Autodiscipline", "value": "34", "type": "number"},
                                                         {"name": "Autodiscipline", "value": "1", "type": "number"},
                                                         {"name": "Autodiscipline", "value": "26", "type": "number"},
                                                         {"name": "Autodiscipline", "value": "0", "type": "number"},
                                                         {"name": "Controle de soi", "value": "34", "type": "number"},
                                                         {"name": "Controle de soi", "value": "3", "type": "number"},
                                                         {"name": "Controle de soi", "value": "26", "type": "number"},
                                                         {"name": "Controle de soi", "value": "0", "type": "number"},
                                                         {"name": "Recherche de réussite", "value": "26",
                                                          "type": "number"},
                                                         {"name": "Recherche de réussite", "value": "0",
                                                          "type": "number"},
                                                         {"name": "Recherche de réussite", "value": "18",
                                                          "type": "number"},
                                                         {"name": "Recherche de réussite", "value": "0",
                                                          "type": "number"},
                                                         {"name": "Proactivité", "value": "15", "type": "number"},
                                                         {"name": "Proactivité", "value": "0", "type": "number"},
                                                         {"name": "Proactivité", "value": "9", "type": "number"},
                                                         {"name": "Proactivité", "value": "0", "type": "number"},
                                                         {"name": "Ouverture", "value": "98", "type": "number"},
                                                         {"name": "Ouverture", "value": "0", "type": "number"},
                                                         {"name": "Ouverture", "value": "82", "type": "number"},
                                                         {"name": "Ouverture", "value": "0", "type": "number"},
                                                         {"name": "Caractère consciencieux", "value": "85",
                                                          "type": "number"},
                                                         {"name": "Caractère consciencieux", "value": "0",
                                                          "type": "number"},
                                                         {"name": "Caractère consciencieux", "value": "71",
                                                          "type": "number"},
                                                         {"name": "Caractère consciencieux", "value": "0",
                                                          "type": "number"},
                                                         {"name": "Extraversion", "value": "69", "type": "number"},
                                                         {"name": "Extraversion", "value": "0", "type": "number"},
                                                         {"name": "Extraversion", "value": "55", "type": "number"},
                                                         {"name": "Extraversion", "value": "0", "type": "number"},
                                                         {"name": "Agréabilité", "value": "134", "type": "number"},
                                                         {"name": "Agréabilité", "value": "6", "type": "number"},
                                                         {"name": "Agréabilité", "value": "116", "type": "number"},
                                                         {"name": "Agréabilité", "value": "2", "type": "number"},
                                                         {"name": "Stabilité émotionnelle", "value": "126",
                                                          "type": "number"},
                                                         {"name": "Stabilité émotionnelle", "value": "5",
                                                          "type": "number"},
                                                         {"name": "Stabilité émotionnelle", "value": "110",
                                                          "type": "number"},
                                                         {"name": "Stabilité émotionnelle", "value": "3",
                                                          "type": "number"}]}, "reports": {"items": [
                                                         {"name": "PfPI Profile Report", "type": "pdf",
                                                          "url": "https://report.sandbox.eu.connect.talentlens.com/report-fr-18edaaed-a702-4689-93ed-d16715ba0c32",
                                                          "languageCode": "fr"},
                                                         {"name": "PfPI Profile Report", "type": "pdf",
                                                          "url": "https://report.sandbox.eu.connect.talentlens.com/report-de-DE-972f02e8-164f-4c63-8ed6-f29c1a23b321",
                                                          "languageCode": "de-DE"},
                                                         {"name": "PfPI Profile Report", "type": "pdf",
                                                          "url": "https://report.sandbox.eu.connect.talentlens.com/report-en-GB-ce4291ee-226e-4479-83eb-5d85861fddb5",
                                                          "languageCode": "en-GB"},
                                                         {"name": "PfPI Profile Report", "type": "pdf",
                                                          "url": "https://report.sandbox.eu.connect.talentlens.com/report-nl-547ba32a-44c9-4141-b952-c94aa73f1c29",
                                                          "languageCode": "nl"},
                                                         {"name": "PfPI Profile Report", "type": "pdf",
                                                          "url": "https://report.sandbox.eu.connect.talentlens.com/report-nl-BE-f00a8d23-bbf7-4818-b3dd-a070532d5361",
                                                          "languageCode": "nl - BE"}]}}}]}]}}
